name: Call Reusable Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main 

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      node: 14
